//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceUI.ShoppingCartServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShoppingCartServiceReference.IShoppingCartServices")]
    public interface IShoppingCartServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartServices/CartGetAll", ReplyAction="http://tempuri.org/IShoppingCartServices/CartGetAllResponse")]
        ModelPOCO.ShoppingCart[] CartGetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartServices/CartGetAll", ReplyAction="http://tempuri.org/IShoppingCartServices/CartGetAllResponse")]
        System.Threading.Tasks.Task<ModelPOCO.ShoppingCart[]> CartGetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartServices/CartAdd", ReplyAction="http://tempuri.org/IShoppingCartServices/CartAddResponse")]
        int CartAdd(ModelPOCO.ShoppingCart entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartServices/CartAdd", ReplyAction="http://tempuri.org/IShoppingCartServices/CartAddResponse")]
        System.Threading.Tasks.Task<int> CartAddAsync(ModelPOCO.ShoppingCart entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartServices/UpdateCart", ReplyAction="http://tempuri.org/IShoppingCartServices/UpdateCartResponse")]
        void UpdateCart(ModelPOCO.ShoppingCart entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartServices/UpdateCart", ReplyAction="http://tempuri.org/IShoppingCartServices/UpdateCartResponse")]
        System.Threading.Tasks.Task UpdateCartAsync(ModelPOCO.ShoppingCart entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartServices/DeleteCart", ReplyAction="http://tempuri.org/IShoppingCartServices/DeleteCartResponse")]
        void DeleteCart(ModelPOCO.ShoppingCart entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartServices/DeleteCart", ReplyAction="http://tempuri.org/IShoppingCartServices/DeleteCartResponse")]
        System.Threading.Tasks.Task DeleteCartAsync(ModelPOCO.ShoppingCart entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartServices/FindCart", ReplyAction="http://tempuri.org/IShoppingCartServices/FindCartResponse")]
        ModelPOCO.ShoppingCart FindCart(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartServices/FindCart", ReplyAction="http://tempuri.org/IShoppingCartServices/FindCartResponse")]
        System.Threading.Tasks.Task<ModelPOCO.ShoppingCart> FindCartAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShoppingCartServicesChannel : ECommerceUI.ShoppingCartServiceReference.IShoppingCartServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShoppingCartServicesClient : System.ServiceModel.ClientBase<ECommerceUI.ShoppingCartServiceReference.IShoppingCartServices>, ECommerceUI.ShoppingCartServiceReference.IShoppingCartServices {
        
        public ShoppingCartServicesClient() {
        }
        
        public ShoppingCartServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShoppingCartServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingCartServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingCartServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ModelPOCO.ShoppingCart[] CartGetAll() {
            return base.Channel.CartGetAll();
        }
        
        public System.Threading.Tasks.Task<ModelPOCO.ShoppingCart[]> CartGetAllAsync() {
            return base.Channel.CartGetAllAsync();
        }
        
        public int CartAdd(ModelPOCO.ShoppingCart entity) {
            return base.Channel.CartAdd(entity);
        }
        
        public System.Threading.Tasks.Task<int> CartAddAsync(ModelPOCO.ShoppingCart entity) {
            return base.Channel.CartAddAsync(entity);
        }
        
        public void UpdateCart(ModelPOCO.ShoppingCart entity) {
            base.Channel.UpdateCart(entity);
        }
        
        public System.Threading.Tasks.Task UpdateCartAsync(ModelPOCO.ShoppingCart entity) {
            return base.Channel.UpdateCartAsync(entity);
        }
        
        public void DeleteCart(ModelPOCO.ShoppingCart entity) {
            base.Channel.DeleteCart(entity);
        }
        
        public System.Threading.Tasks.Task DeleteCartAsync(ModelPOCO.ShoppingCart entity) {
            return base.Channel.DeleteCartAsync(entity);
        }
        
        public ModelPOCO.ShoppingCart FindCart(int ID) {
            return base.Channel.FindCart(ID);
        }
        
        public System.Threading.Tasks.Task<ModelPOCO.ShoppingCart> FindCartAsync(int ID) {
            return base.Channel.FindCartAsync(ID);
        }
    }
}
